### ISSUE TITLE
Not working on heroku , is it possible to run it on vps?

### ISSUE THREAD

**Issue by iamLiquidX** [jaskaranSM/HerokuManagerBot#1]
sir the bot is not working on heroku. is it possible to launch it on other vps ? it would be great addition if you can update this repo

**Comment by JaskaranSM** [comment]
Regarding the heroku case: May i see Error traceback (plain not working doesnt make much sense) ? You are supposed to push it to heroku with heroku-cli
Regarding vps: install requirements and run start.sh shell script

**Comment by iamLiquidX** [comment]
> Regarding the heroku case: May i see Error traceback (plain not working doesnt make much sense) ? You are supposed to push it to heroku with heroku-cli
> Regarding vps: install requirements and run start.sh shell script

i will redeploy using cli and let you know the results...

**Comment by iamLiquidX** [comment]
> Regarding the heroku case: May i see Error traceback (plain not working doesnt make much sense) ? You are supposed to push it to heroku with heroku-cli
> Regarding vps: install requirements and run start.sh shell script

Here is the log of error https://del.dog/lopudifugn.txt

**Comment by iamLiquidX** [comment]
I have edited the config.py, i connected the app using heroku cli , set stack as container and then pushed

**Comment by JaskaranSM** [comment]
> I have edited the config.py, i connected the app using heroku cli , set stack as container and then pushed

I see wat u edited in config.py, thats bad and wont gonna work. i suggest to reset the changes, config loads in those variables from system environment variables, heroku provides interface to set them from their web ui. After setting them restart the app.

**Comment by iamLiquidX** [comment]
> > I have edited the config.py, i connected the app using heroku cli , set stack as container and then pushed
> 
> I see wat u edited in config.py, thats bad and wont gonna work. i suggest to reset the changes, config loads in those variables from system environment variables, heroku provides interface to set them from their web ui. After setting them restart the app.

there is no config veriable showing in heroku settings

**Comment by iamLiquidX** [comment]
i will also try with no modification and let you know the results

**Comment by JaskaranSM** [comment]
> > > I have edited the config.py, i connected the app using heroku cli , set stack as container and then pushed
> > 
> > 
> > I see wat u edited in config.py, thats bad and wont gonna work. i suggest to reset the changes, config loads in those variables from system environment variables, heroku provides interface to set them from their web ui. After setting them restart the app.
> 
> there is no config veriable showing in heroku settings

![20210122_160326](https://user-images.githubusercontent.com/37726998/105480227-78d0d300-5ccb-11eb-9868-cb4924ebee3b.jpg)
Settings -> config vars

**Comment by iamLiquidX** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/66400864/105480396-b46b9d00-5ccb-11eb-91c9-93af06c7d5de.png)

not showing up after deploying

**Comment by JaskaranSM** [comment]
> ![Screenshot_1](https://user-images.githubusercontent.com/66400864/105480396-b46b9d00-5ccb-11eb-91c9-93af06c7d5de.png)
> 
> not showing up after deploying

It would seems you have no idea how to use heroku, and yet you are trying to deploy a heroku management bot. Those key value boxes are there for setting environment variables

**Comment by iamLiquidX** [comment]
> > ![Screenshot_1](https://user-images.githubusercontent.com/66400864/105480396-b46b9d00-5ccb-11eb-91c9-93af06c7d5de.png)
> > not showing up after deploying
> 
> It would seems you have no idea how to use heroku, and yet you are trying to deploy a heroku management bot. Those key value boxes are there for setting environment variables

so i have to set them manually.. my apologies for wasting ur time.....

**Comment by iamLiquidX** [comment]
i am dumb..and nooob af
